openapi: 3.1.0
info:
  version: 1.0.0
  title: Fabriq API
  x-logo:
    url: 'https://web-assets.bcg.com/20/56/be8ad508416aa337532210a2527e/fabriq-logo.svg'
  description:
    $ref: ./info-description.md
tags:
  - name: Events
    description: >-
      Activations, transactions and actions progress customers offers and
      trigger the issuance of rewards
    externalDocs:
      description: >-
        Coming soon: Our Transactions developer documents are being finalized.
        Check back soon for updates.
      url: https://docs.formation.ai/transactions
  - name: Status
    description: >-
      Request the offers that a customer currently has active as well as their
      current progress.
  - name: Customer Management
    description: Manage your customer information within the platform
servers:
  - url: https://api.fabriq.bcg.com
    description: Production Server
paths:
  /v1/transaction:
    $ref: './paths/v1_transaction.yaml'
  /v1/action:
    $ref: './paths/v1_action.yaml'
  /v1/activation:
    $ref: './paths/v1_activation.yaml'
  /customers/forget:
    $ref: './paths/customers_forget.yaml'
  /status/{CustomerID}:
    $ref: './paths/status_{CustomerID}.yaml'
components:
  securitySchemes:
    api_key:
      in: header
      name: x-api-key
      type: apiKey
